name: AgeOfWar
version: 1.0
author: ArchMageGaming
main: me.ArchMageGaming.AgeOfWar.Main

commands:
  hello:
   aliases: [hi]
   description: This is the hello command!
  join:
   aliases: [faction]
   description: Joins a Faction
